=head1 NAME

Change log for B<psh2> - The Perl SHell 2

=head1 DESCRIPTION

A reverse-chronological ordered list of changes

=cut

# This is so pod2man won't complain ;-)


###############################################################################
###############################################################################
##
## CVS
##
###############################################################################
###############################################################################

=head1 0.001 [2003-01-03]

=over 4

=item *

Start of development of new version

=back
