#! /usr/bin/perl -w

$Psh2::VERSION='0.001';

require Psh2;

my $psh= new Psh2();
my %opt=();

if (@ARGV) {
    require Getopt::Std;
    Getopt::Std::getopts('Vifhc:', \%opt);
    if ($opt{'V'}) {
	print "psh2, version $Psh2::VERSION\nCopyright (c) 1999-2003 psh Core Team\n";
	exit 1;
    }
    if ($opt{'h'}) {
	print <<ENDOFHELP;
Usage: psh2 [option] ...
       psh2 [option] script-file ...

Options:
       -V  print version and exit         -h  show this help
       -i  force reading of rc files      -f  skip reading rc files
       -c  execute command

Use 'man psh' or 'psh2 -c help' for more information.
ENDOFHELP
	exit 1;
    }
}

$psh->init_minimal();
$psh->process_rc() unless ($opt{'f'} or $opt{'c'} or @ARGV) and !$opt{'i'};
$psh->init_finish();

if ($opt{'c'}) {
    $psh->process_variable($opt{'c'});
    exit ($psh->{status}?0:2);
}

if (@ARGV) {
    $psh->process_args(@ARGV);
} else {
    $psh->init_interactive();
    $psh->main_loop();
}

exit(!$psh->{status});
